### ISSUE TITLE
Improve style for guilabel and menuselection

### ISSUE THREAD

**Issue by stevepiercy** [plone/training#545]
`guilabel` and `menuselection` are frequently used directives, but they lack any styling. I think that there was styling for them in the past.

Here's the rendered HTML.

`<span class="menuselection">Volto → add-ons → project</span>`

`<span class="guilabel">Volto → add-ons → project</span>`

Here's suggested CSS.

```css
.guilabel, .menuselection {
    border: 1px solid #7fbbe3;
    background: #e7f2fa;
    border-radius: 4px;
    padding: 2.4px 6px;
    font-weight: bold;
    font-style: italic;
}
```

Before and after.
![Screen Shot 2021-10-18 at 12 34 46 AM](https://user-images.githubusercontent.com/102112/137687958-63a7adc1-5ca7-4f87-a429-c6f5a496f27b.png)
